# Generated by Django 4.1.4 on 2023-02-07 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RussianWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=75, verbose_name='Cлово')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=75, verbose_name='Cлово')),
                ('transcription', models.CharField(blank=True, max_length=75, verbose_name='Транскрипция')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования')),
                ('irregular_verbs', models.BooleanField(default=False, verbose_name='Не правильный глагол')),
                ('audi', models.FileField(blank=True, upload_to='audi/%Y/%m/%d', validators=[django.core.validators.RegexValidator(regex='.mp3')], verbose_name='Произношение')),
                ('value', models.ManyToManyField(to='dictionaries.russianword', verbose_name='Русское значение')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['-created'],
            },
        ),
    ]
